#ifndef CONFIG_H_INCLUDED
#define CONFIG_H_INCLUDED

#define SERIAL_BAUDRATE 115200
#define LOOP_DELAY 5000

#define AUTOCONNECT_SSID "MQTT-Home-Monitor"
#define AUTOCONNECT_PASSWORD "password"

#endif
